@url = http://127.0.0.1:5000

### Create tasks
# @name create
POST {{url}}/tasks 
content-type: application/json

{
  "title": "Task Example",
  "description": "Any example task"
}

### Get tasks
GET {{url}}/tasks 

### Get task by id
GET {{url}}/tasks/{{create.response.body.id}}

### Update task by id
PUT {{url}}/tasks/{{create.response.body.id}}
content-type: application/json

{
  "title": "Task Example",
  "description": "Any example task updated",
  "completed": true
}

### Delete task by id
DELETE {{url}}/tasks/{{create.response.body.id}}
content-type: application/json